### ISSUE TITLE
First vertical slash missed

### ISSUE THREAD

**Issue by asdf8601** [jakebathman/Markdown-Table-Generator#2]
Hi, very useful too, nice work! 👍 

My feedback, after paste my table, It's missed the first " | ", when you have a big table it is some annoying. 

Bests!

**Comment by jakebathman** [comment]
Hey there!

Can you give me an example of what you pasted in? I'll take a look and get it fixed!

**Comment by asdf8601** [comment]
Of course,

### My paste:

```
FO  51.1875                 
PRECIO  0.15    0.22                
CANTIDAD    93.75   168.75              
CESTA   A   B   LHS     RHS Holgura
TOMATES 0.33    1.00    200 ≤ 200 0
LECHUGA 1.00    0.33    150 ≤ 150 0
HUEVOS  0.72    0.72    189 ≤ 300 111
```

### Here capture:

![captura de pantalla 2016-05-14 a las 6 51 11 pm](https://cloud.githubusercontent.com/assets/6231413/15269623/26e08080-1a05-11e6-9c77-cc812627d8a8.png)

**Comment by jakebathman** [comment]
Great documentation, thanks. I'll take a look to see what's going on and mention you when it's fixed.

**Comment by jakebathman** [comment]
It looks like the markdown wasn't broken, but the helper that I was using to show the HTML version.

I've switched to another one, and it should be working fine for you now. Thanks for the report!
